#
# Nginx, Laravel, MySQL
#
# Source
# https://github.com/faerulsalamun/docker-nginx-laravel-mysql

FROM nginx
MAINTAINER Faerul Salamun <faerulsalamun@gmail.com>

COPY ./default.conf /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]
